spring:
  datasource:
      url: jdbc:postgresql://127.0.0.1:5432/examples
      username: postgres
      password: postgres
      poolSize: 30
      driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate.ddl-auto: validate

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect